name: Build & Push
on:
  push:
    branches: [ develop, main ]
jobs:
  build:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
