name: CI (PR checks)
on:
  pull_request:
    branches: [ dev, main ]
    paths:
      - "backend/**"
      - "frontend/**"
      - "k8s/**"
      - "Dockerfile"
      - ".github/workflows/**"
permissions: { contents: read }
jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python deps & run tests
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f pytest.ini ] || [ -f conftest.py ]; then pytest -q --maxfail=1 --disable-warnings; else echo "No tests"; fi
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node deps & run tests
        working-directory: frontend
        run: |
          if [ -f package-lock.json ]; then npm ci; elif [ -f package.json ]; then npm i; fi
          if [ -f package.json ]; then npm test --silent || true; fi
