name: Deploy

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Container tag to deploy (default: latest)"
        required: false
        default: "latest"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Azure login (Service Principal)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS credentials
        run: az aks get-credentials --resource-group sit722-w09-rg --name sit722-w09-aks --overwrite-existing

      - name: Rollout web deployment
        env:
          ACR_SERVER: sit722w09zaidregistry.azurecr.io   # <-- your ACR login server
          TAG: ${{ inputs.image_tag }}
        run: |
          # Replace 'app' and 'web' if your image/deployment names differ
          kubectl set image deployment/web web=$ACR_SERVER/app:$TAG
          kubectl rollout status deployment/web --timeout=180s

      - name: Show services
        run: kubectl get svc -A -o wide
