name: Frontend CI - Build & Push Image

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend_ci.yml'

env:
  # MUST be a repo secret with value: sit722acr9165.azurecr.io (no spaces/newlines)
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
  IMAGE_TAG: ${{ github.sha }}-${{ github.run_id }}

jobs:
  build_and_push_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Clean/normalize and derive short ACR name for `az acr login`
      - name: Normalize ACR vars
        shell: bash
        run: |
          CLEAN="$(echo -n "${ACR_LOGIN_SERVER}" | tr -d '\r\n' | xargs)"
          echo "ACR_LOGIN_SERVER=$CLEAN" >> "$GITHUB_ENV"
          echo "ACR_NAME=${CLEAN%%.*}"   >> "$GITHUB_ENV"

      - name: Login to Azure Container Registry
        run: az acr login --name "$ACR_NAME"

      - name: Build and Push Frontend Image
        run: |
          docker build -t "$ACR_LOGIN_SERVER/frontend:latest" ./frontend/
          docker push "$ACR_LOGIN_SERVER/frontend:latest"

      - name: Logout from Azure
        if: always()
        run: az logout
