name: Reusable Build & Push

on:
  workflow_call:
    inputs:
      registry:         # e.g. sit722w09zaidregistry.azurecr.io
        required: true
        type: string
      image_name:       # e.g. product_service
        required: true
        type: string
      context:          # e.g. ./backend/product_service
        required: true
        type: string
      dockerfile:       # e.g. ./backend/product_service/Dockerfile
        required: true
        type: string
      push:             # true on develop/main
        required: true
        type: boolean
    outputs:
      digest:
        description: Image digest from build-push
        value: ${{ jobs.build-push.outputs.digest }}

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      digest: ${{ steps.build.outputs.digest }}
    steps:
      - uses: actions/checkout@v4

      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.registry }}/${{ inputs.image_name }}
          tags: |
            type=sha
            type=ref,event=tag
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id:       ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:       ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: ACR login
        uses: azure/docker-login@v2
        with:
          login-server: ${{ inputs.registry }}

      - id: build
        uses: docker/build-push-action@v6
        with:
          context:   ${{ inputs.context }}
          file:      ${{ inputs.dockerfile }}
          push:      ${{ inputs.push }}
          cache-from: type=gha
          cache-to:   type=gha,mode=max
          sbom: true
          provenance: true
          tags:   ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
