name: Reusable Build
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      ACR_NAME:   sit722w09zaidregistry
      ACR_SERVER: sit722w09zaidregistry.azurecr.io
      TAG:        ${{ github.sha }}
    steps:
      - uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id:       ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:       ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: ACR login
        uses: azure/docker-login@v2
        with:
          login-server: ${{ env.ACR_SERVER }}

      - name: Build & push product_service
        run: |
          docker build -t $ACR_SERVER/product_service:${TAG} -t $ACR_SERVER/product_service:latest ./backend/product_service
          docker push  $ACR_SERVER/product_service:${TAG}
          docker push  $ACR_SERVER/product_service:latest

      - name: Build & push order_service
        run: |
          docker build -t $ACR_SERVER/order_service:${TAG} -t $ACR_SERVER/order_service:latest ./backend/order_service
          docker push  $ACR_SERVER/order_service:${TAG}
          docker push  $ACR_SERVER/order_service:latest

      - name: Build & push frontend
        run: |
          docker build -t $ACR_SERVER/frontend:${TAG} -t $ACR_SERVER/frontend:latest ./frontend
          docker push  $ACR_SERVER/frontend:${TAG}
          docker push  $ACR_SERVER/frontend:latest
